### PR TITLE
Support 64 bits Pharo

### PR DESCRIPTION
**Pull request by guillep**
Support 64 bits require coercions to be done depending on the platform.
Using size-agnostic setters for that.

### CODE REVIEW

**Comment by marianopeck** [comment]
Thanks @guillep 

This is very cool. I thought there were a few more cases to fix pointers... those where the only 2?? great!

BTW, do you know what's the status of the Travis on Pharo?  still see some random failures on the Travis results of this PR so I really don't know if all tests passes or nor on all platforms. Any thought?

As a reminder  to myself (or in case you can add this too to this PR)... There is a lot of OSProcess (yes, OSProcess) that we are currently using because we don't have https://github.com/pharo-project/pharo-vm/pull/142 integrated in the VM. But that will be merged soon. When that is merged, then I think we can recover a commit I did long ago on the dev branch: https://github.com/marianopeck/OSSubprocess/commit/5d88003c093a2692a40e4612b6f57611b1d9f02e

As you can see, that commit bings some pointer calculation that would need fixing for 32 vs 64 bits, but it would cut a big dependency I currently have on OSProcess primitives. 

Do you think you can take a look ?

**Comment by akgrant43** [comment]
Have you run the automated tests with these patches?

Loading with:

Metacello new
	configuration: 'OSSubprocess';
	repository: 'github://guillep/OSSubprocess:support64bits/repository';
	load.

And running OSSFileBasedUnixSubprocessTest tests from the browser results in the image terminating with the following to stdout:

$ ./pharo-ui Pharo7.0-64bit-1da1c02.image 
pharo  Pharo7.0-32bit-1da1c02.sources  Pharo7.0-64bit-1da1c02.changes  Pharo7.0-64bit-1da1c02.image  pharo-local  pharo-ui  pharo-vm
/dev/shm/p64/Pharo7.0-64bit-1da1c02.image
pharo  Pharo7.0-32bit-1da1c02.sources  Pharo7.0-64bit-1da1c02.changes  Pharo7.0-64bit-1da1c02.image  pharo-local  pharo-ui  pharo-vm
pharo  Pharo7.0-32bit-1da1c02.sources  Pharo7.0-64bit-1da1c02.changes  Pharo7.0-64bit-1da1c02.image  pharo-local  pharo-ui  pharo-vm
pharo  Pharo7.0-32bit-1da1c02.sources  Pharo7.0-64bit-1da1c02.changes  Pharo7.0-64bit-1da1c02.image  pharo-local  pharo-ui  pharo-vm
/bin/ls: cannot access 'whatever': No such file or directory
pharo  Pharo7.0-32bit-1da1c02.sources  Pharo7.0-64bit-1da1c02.changes  Pharo7.0-64bit-1da1c02.image  pharo-local  pharo-ui  pharo-vm
pharo  Pharo7.0-32bit-1da1c02.sources  Pharo7.0-64bit-1da1c02.changes  Pharo7.0-64bit-1da1c02.image  pharo-local  pharo-ui  pharo-vm
Terminated

I don't get a crash dump or any other notification.

Ubuntu 16.04

$ ./pharo --version
5.0-201802281359  Wed Feb 28 14:02:53 UTC 2018 c99 [Production Spur 64-bit VM]
CoInterpreter VMMaker.oscog-eem.2320 uuid: e2692e35-5fc8-4623-95d0-b445b3329f75 Feb 28 2018
StackToRegisterMappingCogit VMMaker.oscog-eem.2324 uuid: 904abc56-e5a8-467e-a337-880211e33805 Feb 28 2018
VM: 201802281359 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $ Date: Wed Feb 28 14:59:26 2018 +0100 $
Plugins: 201802281359 https://github.com/OpenSmalltalk/opensmalltalk-vm.git $
Linux travis-job-d495c0d0-285c-4587-b9a2-f40e613b2028 4.4.0-101-generic #124~14.04.1-Ubuntu SMP Fri Nov 10 19:05:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
plugin path: /dev/shm/p64/pharo-vm/lib/pharo/5.0-201802281359 [default: /dev/shm/p64/pharo-vm/lib/pharo/5.0-201802281359/]

I'm not necessarily suggesting the patch is incorrect, just wondering whether it is enough, or if more work is required.

Thanks,
Alistair

**Comment by guillep** [comment]
I only tested the examples doing /bin/ls or similar.
I saw the failing tests afterwards.
The thing is that I was too busy before to keep going on this ^^.

I'm doing a pass on it now to see if there are other similar problems to fix that would solve this.

**Comment by guillep** [comment]
Well, tests seem to be working now in Pharo 6.1 and 7.0.

https://travis-ci.org/marianopeck/OSSubprocess/builds/349217632

To fix the CI we only raised with @tesonep the tests default timeout:

https://github.com/guillep/OSSubprocess/commit/ec85b4a3bf7d714c135d0ee386bc5cb68bdfd15f#diff-27fb966f689816da3dea68ad7cea0911

The only remaining problem is that 64 bit support depends on some UFFI extensions that are only available for Pharo6+, thus Pharo 5 support is broken with this version. This could be solved either moving that method to OSSubprocess, or by adding a compatibility package for Pharo 5. Or, we could just say that versions >0.3 do not work on Pharo5?

**Comment by marianopeck** [comment]
Hi @guillep 

"we could just say that versions >0.3 do not work on Pharo5?"  Yes, I would do so. In fact, there are other changes I would like to make that are only in Pharo 7.0 VM. So I would simply assume certain releases up to certain Pharo releases...  So for example, 0.25 should be < Pharo 6.  The next 3.0 could be for Pharo 6 and 7 etc. 

BTW, you said travis is running but as far as I can see it is only running the 32 bits Pharo, right? 
Is there a way to update travis.yml so that it also tests 64 flavors?

**Comment by guillep** [comment]
Well, my last commits should have:
 - added 64 build CI jobs
 - made jobs go green

Current build in here: https://travis-ci.org/guillep/OSSubprocess

**Comment by marianopeck** [comment]
Hi @guillep 

Excellent! Thank you very much. I created a new branch `support64bits` and I tried to accept this PR into that new branch rather than in the master, but I failed. Git complains with a `There are no new commits between base branch 'support64bits' and head branch 'support64bits'`. I wanted to have a branch so that I can easily make any further changes or that users can point directly to the branch to give it a try, without affecting `master`. Any idea how to do it?

**Comment by guillep** [comment]
It looks like the branch is already there. Maybe i pushed my branch to this repo by mistake? In any case it is already done!

**Comment by marianopeck** [comment]
Hi @guillep 

Yeah..I think I finally created the branch, then I merged your commits there... 

BTW, any clue on why the travis failing  #testSigTermInsideLoop of  #35.13 failed ?

Thanks

**Comment by guillep** [comment]
No idea, I retried and it passed...

**Comment by guillep** [comment]
Mariano, can we integrate this? I need this for getting iceberg tests pass on 64 bits :)

**Comment by marianopeck** [comment]
Sure. Thanks @guillep for the reminder. I should also make a new release soon...

**Comment by akgrant43** [comment]
Hi Mariano,

Don't forget that with a new stable VM we now have:

FilePluginPrims>>connectToFileDescriptor:writable:
FilePluginPrims>>connectToFile:writable:

available.

Cheers,
Alistair

**Comment by guillep** [comment]
@marianopeck I'm waiting for it :)

**Comment by marianopeck** [comment]
for the release?

**Comment by guillep** [comment]
> @guillep for the release?

Yes. I want to have 64 bit support on iceberg and that's something missing.

The commit integrating this PR seems working!

https://travis-ci.org/pharo-vcs/iceberg/builds/377776150

**Pull request merged**
